import type { PlayerCard, PlayerDetails, WorldItem } from './footballWorld';

const english:Record<string,string>={
  'Усман Дембеле':'Ousmane Dembélé','Айтана Бонмати':'Aitana Bonmatí','Ламин Ямаль':'Lamine Yamal','Килиан Мбаппе':'Kylian Mbappé','Лионель Месси':'Lionel Messi','Эрлинг Холанд':'Erling Haaland','Харри Кейн':'Harry Kane','Хвича Кварацхелия':'Khvicha Kvaratskhelia','Хулиан Альварес':'Julián Álvarez','Луис Энрике':'Luis Enrique','Ханси Флик':'Hansi Flick','Арне Слот':'Arne Slot',
  'Франция':'France','Испания':'Spain','Аргентина':'Argentina','Норвегия':'Norway','Англия':'England','Грузия':'Georgia','Германия':'Germany','Нидерланды':'Netherlands','Париж':'Paris','Мадрид':'Madrid','Барселона':'Barcelona','Ливерпуль':'Liverpool',
  'Правая':'Right','Левая':'Left','3× подряд The Best FIFA':'3× consecutive The Best FIFA','2-е место The Best FIFA 2025':'2nd place · The Best FIFA 2025','3-е место The Best FIFA 2025':'3rd place · The Best FIFA 2025','Победитель Лиги чемпионов 2025':'2025 Champions League winner','Рекордсмен Лиги чемпионов':'Most Champions League titles','Контроль мяча и школа La Masia':'Possession football and La Masia','Интенсивность и быстрый прессинг':'Intensity and fast pressing','Финалист The Best FIFA 2025':'The Best FIFA 2025 finalist',
  '8 голов · 3 передачи':'8 goals · 3 assists','8 голов · 2 передачи':'8 goals · 2 assists','7 голов на ЧМ-2026':'7 goals at World Cup 2026','6 голов · 1 передача':'6 goals · 1 assist','Игрок сезона ЛЧ':'Champions League player of the season','Лучший бомбардир ЛЧ':'Champions League top scorer','14 голов в ЛЧ':'14 Champions League goals','10 голов в ЛЧ':'10 Champions League goals',
  'Взрывная скорость, рывки за спину и точное завершение атак.':'Explosive pace, runs in behind and clinical finishing.','Контроль мяча, видение поля и передачи между линиями.':'Close control, vision and passes between the lines.','Мощные рывки, выбор позиции и игра в штрафной площади.':'Powerful runs, smart positioning and elite box play.','Завершение атак, дальние передачи и умное движение без мяча.':'Finishing, long passing and intelligent movement.','Дриблинг один в один, смена направления и удары с фланга.':'One-on-one dribbling, sharp turns and shots from the wing.','Интенсивный прессинг, движение между линиями и быстрые удары.':'Intense pressing, movement between lines and quick finishing.',
  'ГОЛ':'GLS','ПАС':'AST','УД':'SHT','МАТ':'APP','СКР':'CHC',
};

const translate=(value:string)=>Object.entries(english).reduce((result,[source,target])=>result.split(source).join(target),value);
export const localizeWorldItem=(item:WorldItem,language:'ru'|'en')=>language==='en'?{name:translate(item.name),meta:translate(item.meta),fact:translate(item.fact)}:{name:item.name,meta:item.meta,fact:item.fact};
export const localizePlayerCard=(card:PlayerCard,language:'ru'|'en')=>language==='en'?{name:translate(card.name),country:translate(card.country),note:translate(card.note),stats:card.stats.map((stat)=>({...stat,label:translate(stat.label)}))}:{name:card.name,country:card.country,note:card.note,stats:card.stats};
export const localizePlayerDetails=(details:PlayerDetails,language:'ru'|'en')=>language==='en'?{...details,nationalTeam:translate(details.nationalTeam),foot:translate(details.foot),height:details.height.replace(' см',' cm'),style:translate(details.style)}:details;
