import { useState } from 'react';
import { Goalkeeper } from './Goalkeeper';

type Direction='left'|'center'|'right';
const directions:{id:Direction;label:string;icon:string}[]=[{id:'left',label:'Прыжок влево',icon:'↖'},{id:'center',label:'Остаться в центре',icon:'↑'},{id:'right',label:'Прыжок вправо',icon:'↗'}];
const randomShot=():Direction=>['left','center','right'][Math.floor(Math.random()*3)] as Direction;
const shotFromCue=(cue:Direction):Direction=>{if(Math.random()<.72)return cue;const other=(['left','center','right'] as Direction[]).filter((item)=>item!==cue);return other[Math.floor(Math.random()*other.length)]};

export function GoalkeeperIQ({language,onBack,onComplete}:{language:'ru'|'en';onBack:()=>void;onComplete?:()=>void}){
  const en=language==='en';
  const [choice,setChoice]=useState<Direction>('center'); const [shot,setShot]=useState<Direction|null>(null);const [cue,setCue]=useState<Direction>(randomShot); const [saves,setSaves]=useState(0); const [round,setRound]=useState(1); const [finished,setFinished]=useState(false);
  const isSave=shot!==null&&shot===choice;
  const defend=()=>{if(shot)return;const nextShot=shotFromCue(cue);setShot(nextShot);if(nextShot===choice)setSaves((value)=>value+1)};
  const next=()=>{if(round===5){onComplete?.();return setFinished(true)}setRound((value)=>value+1);setShot(null);setCue(randomShot())};
  const restart=()=>{setChoice('center');setShot(null);setCue(randomShot());setSaves(0);setRound(1);setFinished(false)};
  const labels={left:en?'Dive left':'Прыжок влево',center:en?'Stay central':'Остаться в центре',right:en?'Dive right':'Прыжок вправо'};
  if(finished)return <section className="keeper-finish"><button className="game-back" onClick={onBack}>← {en?'All games':'Все игры'}</button><div>{saves>=4?'🏆':saves>=2?'🧤':'💪'}</div><span className="step-label">{en?'MATCH COMPLETE':'МАТЧ ЗАВЕРШЁН'}</span><h1>{saves>=4?(en?'A wall in goal!':'Стена в воротах!'):saves>=2?(en?'Great game!':'Хорошая игра!'):(en?'Keep training!':'Продолжай тренироваться!')}</h1><strong>{saves}<small>/ 5 {en?'saves':'сейвов'}</small></strong><p>{saves>=4?(en?'You read the shots brilliantly.':'Ты отлично читаешь удары соперника.'):(en?'Watch the striker and time your dive.':'Следи за разбегом нападающего и меняй направление прыжка.')}</p><button className="play-button" onClick={restart}>{en?'Play again':'Сыграть ещё раз'} ↻</button></section>;
  return <section className="goalkeeper-game"><button className="game-back" onClick={onBack}>← {en?'All games':'Все игры'}</button><div className="keeper-game-heading"><div><div className="eyebrow"><span/> {en?'Mini-game':'Мини-игра'}</div><h1>Goalkeeper IQ</h1><p>{en?'Read the run-up and choose before the shot.':'Прочитай разбег и выбери направление.'}</p></div><div className="penalty-score"><span>{en?'Saves':'Сейвы'}</span><strong>{saves}</strong><small>{en?'Round':'Раунд'} {round} / 5</small></div></div><div className="penalty-game keeper-arena"><div className="stadium-lights"/><div className="goal"><div className="goal-net"/><div className={`keeper ${shot?`keeper--${choice}`:''}`}><Goalkeeper/></div><div className={`shot-ball ${shot?`shot-ball--${shot}`:''}`}>⚽</div>{shot&&<div className={`goal-result ${isSave?'result--goal':'result--save'}`}>{isSave?(en?'SAVE!':'СЕЙВ!'):(en?'GOAL!':'ГОЛ!')}</div>}</div><div className="penalty-spot"/><div className="striker-cue">🏃 {en?'Run-up points':'Разбег направлен'} <strong>{en?({left:'LEFT',center:'CENTRE',right:'RIGHT'} as const)[cue]:({left:'ВЛЕВО',center:'В ЦЕНТР',right:'ВПРАВО'} as const)[cue]}</strong><small>{en?'Watch for a bluff':'Возможен обманный удар'}</small></div><div className="penalty-controls"><span>{en?'Where will you dive?':'Куда прыгнуть?'}</span><div>{directions.map((direction)=><button className={choice===direction.id?'active':''} disabled={shot!==null} onClick={()=>setChoice(direction.id)} key={direction.id}><i>{direction.icon}</i>{labels[direction.id]}</button>)}</div>{shot?<button className="penalty-shoot" onClick={next}>{round===5?(en?'Results':'Результат'):(en?'Next shot':'Следующий удар')} →</button>:<button className="penalty-shoot" onClick={defend}>{en?'Defend':'Защищать'} 🧤</button>}</div></div></section>;
}
