import { useState } from 'react';
import { buyCosmetic,equipCosmetic,cosmetics,type CosmeticItem,type EquippedCosmetics } from '../lib/cosmetics';
import { loadGuestProfile,saveGuestProfile } from '../lib/guestProfile';

type Props={coins:number;owned:string[];equipped:EquippedCosmetics;isGuest:boolean;onChange:(coins:number,owned:string[],equipped:EquippedCosmetics)=>void};
const labels={ball:'Мячи',kit:'Формы',stadium:'Стадионы',frame:'Рамки профиля'} as const;

export function ShopScreen({coins,owned,equipped,isGuest,onChange}:Props){
  const [message,setMessage]=useState('');const [busy,setBusy]=useState('');
  const select=async(item:CosmeticItem)=>{if(equipped[item.category]===item.id)return;setBusy(item.id);setMessage('');try{if(isGuest){const guest=loadGuestProfile();if(!guest.ownedCosmetics.includes(item.id)&&guest.coins<item.price)throw new Error('Недостаточно монет.');const nextOwned=guest.ownedCosmetics.includes(item.id)?guest.ownedCosmetics:[...guest.ownedCosmetics,item.id];const nextCoins=guest.ownedCosmetics.includes(item.id)?guest.coins:guest.coins-item.price;const nextEquipped={...guest.equippedCosmetics,[item.category]:item.id};saveGuestProfile({...guest,coins:nextCoins,ownedCosmetics:nextOwned,equippedCosmetics:nextEquipped});onChange(nextCoins,nextOwned,nextEquipped)}else if(owned.includes(item.id)){onChange(coins,owned,await equipCosmetic(item.id,item.category))}else{const result=await buyCosmetic(item.id);onChange(result.coins,result.owned_cosmetics,result.equipped_cosmetics)}setMessage(`${item.name} выбрано ✓`)}catch(reason){setMessage(reason instanceof Error?reason.message:'Покупка не удалась.')}finally{setBusy('')}};
  return <section className="shop-screen"><div className="shop-heading"><div><div className="eyebrow"><span/> Только косметика</div><h1>Магазин</h1><p>Меняй стиль игры без преимущества над соперниками.</p></div><div className="coin-wallet"><span>FIELD COINS</span><strong>${coins}</strong></div></div>{message&&<div className="wallet-message">{message}</div>}{Object.entries(labels).map(([category,label])=><section className="shop-category" key={category}><h2>{label}</h2><div>{cosmetics.filter((item)=>item.category===category).map((item)=>{const has=owned.includes(item.id),active=equipped[item.category]===item.id;return <button className={active?'active':''} disabled={busy===item.id} onClick={()=>select(item)} key={item.id}><span className={`shop-preview shop-preview--${item.id}`}>{item.preview}</span><strong>{item.name}</strong><small>{active?'Выбрано ✓':has?'Выбрать':item.price===0?'Бесплатно':`$${item.price}`}</small></button>})}</div></section>)}</section>;
}
